### ISSUE TITLE
[Search] [General] Modify URL to reflect current search query

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-app-search#28]
So that copying the link will bring up the same search query

- [ ] Don't refresh the page, just update the URL
- [ ] Use angular 2 best practices for this (don't reinvent the wheel)
- [ ] Make sure query is populated from URL when loading the page
- [ ] Make sure that we handle the default case (no search query)
- [ ] Remove the default 'education' search

**Comment by danielbraun** [comment]
I'm gonna leave this issue for now, it's too angular-specific for me to chew on.

**Comment by YontiLevin** [comment]
assigned to eyal lapid

**Comment by YontiLevin** [comment]
@akariv 
please add eyal lapid so i can assign it to him

**Comment by elpddev** [comment]
This can be implemented by using the [location service](https://angular.io/api/common/Location). 
* on init - get location.path() -> parse params -> set the term field (bind it on the input) -> activate search
* on init - subscribe to location.subscribe -> on each change, set the term field and activate search
* on search -> update location via loation.replace (update only if changed)

But is better to know if the App going to use a router instead and this would collide with that. If the app going to implement Angular Router, then it can be implemented by the route service use that instead of the low level location service.

**Comment by YontiLevin** [comment]
url changes back to null when changing tab
