### ISSUE TITLE
[Search] [Budget Changes] Implement budget change item 

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-app-search#29]
returning as 'national-budget-changes'

**Comment by YontiLevin** [comment]
#11

**Comment by YontiLevin** [comment]
@shaylavi 
check that 👆 issue
it explains the difference between the two kinds of רכש

**Comment by mushon** [comment]
@akariv this is already designed as a search result:
![image](https://user-images.githubusercontent.com/27123/27994380-56e60244-64c5-11e7-8ae1-214ef9e729ce.png)

Is that what this issue is about and if it is not, is it the end-point page for the transaction that is probably something for a different repo and depending on the final approach we take for end-point pages.
