### ISSUE TITLE
infinte scroll - fix scroll location when changing groups

### ISSUE THREAD

**Issue by YontiLevin** [OpenBudget/budgetkey-app-search#49]
assigned to eyal lapid

**Comment by YontiLevin** [comment]
check this out again - 
the last commit broke something

**Comment by akariv** [comment]
The last change broke things because now we don't get 10 results from every type, but 10 results from a unified list (meaning that if there's no budget transfer in that 10 first items then we won't have anything to show).
What we need to do is to to re-fetch results when changing groups (with the specific entity types)
